import Head from 'next/head';
import ArticleCard from '@/features/home/HomeMainPage/ArticleCard';
import { container, main } from './style.css';
import { Blog } from '@/types/blog';

type Props = {
  allPostsData: Blog[];
};

export default function HomeMainPage(allPostsData: Props) {
  console.log('allPostData', allPostsData);

  const items = allPostsData.allPostsData;

  return (
    <>
      <Head>
        <title>Zonoryo Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={main}>
        <div className={container}>
          {items.map((item: Blog) => (
            <ArticleCard key={item.id} item={item} />
          ))}
        </div>
      </main>
    </>
  );
}
