import Head from 'next/head';
import { main } from './style.css';
import type { Blog } from '@/types/blog';
import ArticleList from './ArticleList';

type Props = {
  allPostsData: Blog[];
};

export default function HomeMainPage(allPostsData: Props) {
  const items = allPostsData.allPostsData;

  return (
    <>
      <Head>
        <title>Zonoryo Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={main}>
        <ArticleList items={items} />
      </main>
    </>
  );
}
