import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { client } from '@/libs/microCMS';

const inter = Inter({ subsets: ['latin'] });

//ブログ一覧取得
export const getBlogs = async () => {
  const blog = await client.get({
    endpoint: 'blogs',
  });

  return blog.contents;
};

export async function getStaticProps() {
  const allPostsData = await getBlogs();

  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home(allPostsData: any) {
  return (
    <>
      <Head>
        <title>Zonoryo Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Hello world</div>
      </main>
    </>
  );
}
